// ユーザー自身の依頼・販売案件をタイムラインカード形式で返す関数
export function getMyProjectCards(userId = loggedInUserDataGlobal.id) {
  return dashboardAllProjects
    .filter(p => p.clientId === userId || p.contractorId === userId)
    .map(p => ({
      id: p.id,
      title: p.name,
      by: p.clientId === userId ? p.clientName : p.contractorName,
      value: p.totalAmount,
      nature: p.aiRecommendationScore || 0.7,
      reward: p.totalAmount,
      popularity: p.clientRating?.averageScore || 5,
      description: p.description,
      workImage: p.imageUrl || '',
      type: p.clientId === userId ? 'request' : 'offer',
      isMyProject: true,
    }));
}
// Dummy data for MarketCommandUIPage
export const marketCommandItems = [
  { type: 'request', id: 1, title: 'バックエンド開発', by: 'NextGen Mart', value: 400000, nature: 0.9, reward: 400000, popularity: 8, description: 'Eコマースサイトのバックエンド開発をお願いします。Node.jsとGraphQLの経験者を募集しています。', workImage: 'https://images.unsplash.com/photo-1461749280684-dccba630e2f6?auto=format&fit=crop&w=600&q=80' },
  { type: 'offer', id: 2, title: '高品質なロゴを3案作成します', by: 'Sato Design', value: 50000, nature: 0.2, reward: 50000, popularity: 9, description: 'あなたのビジネスの顔となるロゴを、ヒアリングに基づき3つの異なる方向性で提案します。', workImage: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=600&q=80' },
  { type: 'request', id: 3, title: 'SNSキャンペーン企画', by: 'Growth Hackers', value: 100000, nature: 0.6, reward: 100000, popularity: 5, description: '秋のセールスプロモーションに向けたSNSキャンペーンの企画と運用をお願いします。', workImage: '' },
  { type: 'offer', id: 4, title: '朝採れ有機野菜セット (M)', by: 'Suzuki Farms', value: 3500, nature: 0.1, reward: 3500, popularity: 10, description: '旬の有機野菜を8〜10種類詰め合わせたセットです。新鮮な味をお楽しみください。', workImage: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=600&q=80' },
  { type: 'request', id: 5, title: 'Webサイト翻訳（英→日）', by: 'Global Bridge', value: 80000, nature: 0.7, reward: 80000, popularity: 7, description: '企業Webサイトの英語から日本語への翻訳。IT用語に強い方歓迎。', workImage: '' },
  { type: 'offer', id: 6, title: 'プロカメラマンによる商品撮影', by: 'PhotoPro', value: 30000, nature: 0.5, reward: 30000, popularity: 6, description: 'ECサイト用の商品写真をプロが撮影・レタッチまで対応します。', workImage: 'https://images.unsplash.com/photo-1519125323398-675f0ddb6308?auto=format&fit=crop&w=600&q=80' },
  { type: 'request', id: 7, title: 'YouTube動画編集', by: 'Yamada Channel', value: 20000, nature: 0.8, reward: 20000, popularity: 8, description: 'YouTube用の動画編集。カット・テロップ・BGM挿入など。', workImage: '' },
  { type: 'offer', id: 8, title: 'SEO記事執筆（1本）', by: 'Content Works', value: 12000, nature: 0.3, reward: 12000, popularity: 5, description: 'SEOを意識したWeb記事を1本執筆します。ジャンル相談可。', workImage: '' },
  { type: 'request', id: 9, title: 'アプリUIデザイン', by: 'AppStart', value: 60000, nature: 0.85, reward: 60000, popularity: 9, description: '新規スマホアプリのUIデザイン案を3パターン提案してほしい。', workImage: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&w=600&q=80' },
  { type: 'offer', id: 10, title: 'オンライン英会話レッスン', by: 'English Now', value: 2500, nature: 0.4, reward: 2500, popularity: 7, description: 'ネイティブ講師によるマンツーマン英会話レッスン（1回25分）。', workImage: '' },
  { type: 'request', id: 11, title: 'クラウド会計導入サポート', by: 'SmartBiz', value: 40000, nature: 0.65, reward: 40000, popularity: 6, description: 'freeeやマネーフォワードなどクラウド会計ソフトの導入支援。', workImage: '' },
  { type: 'offer', id: 12, title: 'イラストアイコン作成', by: 'Miki Art', value: 5000, nature: 0.2, reward: 5000, popularity: 8, description: 'SNSやブログ用のオリジナルイラストアイコンを作成します。', workImage: 'https://images.unsplash.com/photo-1515378791036-0648a3ef77b2?auto=format&fit=crop&w=600&q=80' },
];
export const loggedInUserDataGlobal = {
  id: 'user555',
  name: '田中 さとし',
  name_en: 'Satoshi Tanaka',
};

// --- ダミーデータ ---
// --- WorkManagementPage用のプロジェクト配列（バックアップと同じ構造） ---
export const workManagementProjects = [
  {
    id: 1,
    name: 'E-commerce Site',
    client: 'NextGen Mart',
    totalBudget: 1200000,
    deadline: '2025-09-30',
    duration: 40,
    description: '',
    cards: [
      { id: 1, projectId: 1, title: 'UI/UXデザイン設計', status: 'approved', reward: 150000, startDate: '2025-08-11', duration: 10, order: 1 },
      { id: 2, projectId: 1, title: 'フロントエンド開発', status: 'awaiting_approval', reward: 300000, startDate: '2025-08-25', duration: 15, order: 2 },
      { id: 3, projectId: 1, title: 'バックエンド開発', status: 'edited', reward: 400000, startDate: '2025-09-15', duration: 15, order: 3 },
    ],
  },
  {
    id: 2,
    name: 'Brand Launch',
    client: 'Creative Studio',
    totalBudget: 350000,
    deadline: '2025-08-31',
    duration: 20,
    description: '',
    cards: [
      { id: 4, projectId: 2, title: 'ロゴデザイン', status: 'approved', reward: 80000, startDate: '2025-08-12', duration: 8, order: 1 },
      { id: 5, projectId: 2, title: 'LP制作', status: 'revision_needed', reward: 120000, startDate: '2025-08-22', duration: 5, order: 2 },
    ],
  },
  {
    id: 3,
    name: 'Autumn Sales Promotion',
    client: 'Growth Hackers',
    totalBudget: 200000,
    deadline: '',
    duration: '',
    description: '',
    cards: [
      { id: 6, projectId: 3, title: 'SNSキャンペーン企画', status: 'unsent', reward: 100000, startDate: '', duration: '', order: 1 },
    ],
  },
];
export const dashboardAllProjects = [
  // job101
  // id: job1（完了済みロゴリニューアル案件）
  {
    id: 'job1',
    name: '企業ロゴリニューアルプロジェクト',
    name_en: 'Corporate Logo Renewal Project',
    clientName: '山田ベーカリー',
    clientName_en: 'Yamada Bakery',
    clientId: 'user123',
    contractorName: '田中 さとし',
    contractorName_en: 'Satoshi Tanaka',
    contractorId: 'user555',
    contractorResellingRisk: 5,
    clientResellingRisk: 0,
    totalAmount: 180000,
    fundsDeposited: 180000,
    fundsReleased: 180000,
    status: '完了',
    status_en: 'Completed',
    description: '創業50年を迎える老舗ベーカリー「山田ベーカリー」のブランドイメージを一新するためのロゴマーク、タグライン、および基本的なブランドガイドラインの制作。',
    description_en: 'Create a new logo, tagline, and basic brand guidelines for Yamada Bakery, a long-established bakery celebrating its 50th anniversary.',
    deliverables: 'ロゴデータ（AI, PNG, JPG）、ブランドガイドライン（PDF）',
    deliverables_en: 'Logo data (AI, PNG, JPG), brand guidelines (PDF)',
    deliverableDetails: 'ロゴマーク（カラー、モノクロ、反転）、タグライン、基本デザインシステム（カラースキーム、指定フォント）、ブランドガイドライン（使用禁止例含む）',
    deliverableDetails_en: 'Logo mark (color, monochrome, reversed), tagline, basic design system (color scheme, specified fonts), brand guidelines including prohibited usage examples.',
    acceptanceCriteria: '最終承認されたデザイン案通りの納品',
    acceptanceCriteria_en: 'Delivery matches the final approved design proposal.',
    acceptanceCriteriaDetails: '依頼者による最終確認後、承認をもって検収完了とする。',
    acceptanceCriteriaDetails_en: 'Inspection is complete upon final confirmation and approval by the client.',
    scopeOfWork_included: 'ロゴデザイン3案提案、選定案のブラッシュアップ、ブランドガイドライン作成（10ページ程度）',
    scopeOfWork_included_en: 'Propose 3 logo designs, refine the selected design, create brand guidelines (approx. 10 pages).',
    scopeOfWork_excluded: 'ロゴを使用した販促物デザイン（名刺、チラシ等）、ウェブサイトへのロゴ組み込み',
    scopeOfWork_excluded_en: 'Designing promotional materials (business cards, flyers, etc.), incorporating the logo into the website.',
    additionalWorkTerms: '販促物デザインは別途お見積もり。ガイドラインの大幅なページ数増加は追加費用発生の可能性あり。',
    additionalWorkTerms_en: 'Promotional material design will be quoted separately. Significant increase in guideline pages may incur additional costs.',
    agreementDocLink: 'yamada_bakery_agreement_v1.pdf',
    changeOrders: [
      {
        id: 'co1-1',
        date: '2024-07-20',
        description: 'エコバッグ用デザインパターンの追加',
        description_en: 'Additional design pattern for eco-bag',
        agreed: true,
        additionalCost: 20000,
      },
    ],
    communicationLogCount: 42,
    lastUpdate: '2024-08-19 11:00',
    hasDispute: false,
    milestones: [
      {
        id: 'm1-1',
        name: 'ヒアリングと方向性提案',
        name_en: 'Hearing and Direction Proposal',
        amount: 30000,
        status: 'paid',
        status_en: 'Paid',
        dueDate: '2024-07-05',
        startDate: '2024-07-01',
        duration: 4,
        paidDate: '2024-07-06',
        description: '詳細ヒアリング、3つのデザイン方向性を提案。',
        description_en: 'Detailed hearing. Propose 3 design directions.',
        submittedFiles: [
          { name: 'direction_proposal.pdf', date: '2024-07-04' },
        ],
        feedbackHistory: [
          {
            type: 'approval',
            type_en: 'Approval',
            date: '2024-07-05',
            comment: 'B案でお願いします。',
            comment_en: 'Please go with option B.',
          },
        ],
      },
      {
        id: 'm1-2',
        name: 'ロゴデザイン案（3種）提出と選定',
        name_en: 'Logo Design Proposals (3 types) Submission and Selection',
        amount: 70000,
        status: 'paid',
        status_en: 'Paid',
        dueDate: '2024-07-25',
        startDate: '2024-07-06',
        duration: 19,
        paidDate: '2024-07-28',
        description: 'ロゴデザイン案3種作成。展開例も提示。',
        description_en: 'Create 3 logo design proposals. Also present deployment examples.',
        submittedFiles: [{ name: 'logo_drafts.zip', date: '2024-07-24' }],
        feedbackHistory: [
          {
            type: 'feedback',
            type_en: 'Feedback',
            date: '2024-07-25',
            comment: '案2が良いがフォント調整希望。',
            comment_en: 'Option 2 is good, but please adjust the font.',
          },
          { type: 'submission', type_en: 'Submission', date: '2024-07-26', comment: '修正案提出。', comment_en: 'Submitted revised proposal.' },
          {
            type: 'approval',
            type_en: 'Approval',
            date: '2024-07-27',
            comment: 'フォントBで決定。',
            comment_en: 'Font B is selected.',
          },
        ],
      },
      {
        id: 'm1-3',
        name: '最終納品',
        name_en: 'Final Delivery',
        amount: 60000,
        status: 'paid',
        status_en: 'Paid',
        dueDate: '2024-08-18',
        startDate: '2024-07-26',
        duration: 23,
        paidDate: '2024-08-18',
        description: 'ロゴデータ、ブランドガイドライン、各種デザイン案データ。',
        description_en: 'Logo data, brand guidelines, and various design proposal data.',
        submittedFiles: [{ name: 'FINAL_ASSETS.zip', date: '2024-08-17' }],
        feedbackHistory: [
          {
            type: 'approval',
            type_en: 'Approval',
            date: '2024-08-18',
            comment: '完璧です。ありがとうございました。',
            comment_en: 'Perfect. Thank you very much.',
          },
        ],
      },
    ],
    contractorRating: {
      averageScore: 5,
      totalReviews: 1,
      reviews: [
        {
          reviewId: 'r1-yamada',
          projectId: 1,
          clientId: 'user123',
          clientName: '山田ベーカリー',
          clientName_en: 'Yamada Bakery',
          rating: 5,
          comment: '素晴らしいロゴをありがとうございました。',
          comment_en: 'Thank you for the wonderful logo.',
          contractorResponse: 'ありがとうございます！',
          contractorResponse_en: 'Thank you very much!',
          date: '2024-08-19',
          disputeContext: null,
          disputeContext_en: null,
          isFlagged: false,
        },
      ],
    },
    needsClientRating: false,
    imageUrl:
      'https://placehold.co/600x400/10B981/FFFFFF?text=%E3%83%AD%E3%82%B4%E3%83%AA%E3%83%8B%E3%83%A5%E3%83%BC%E3%82%A2%E3%83%AB',
    allowSubcontracting: false,
  },
  {
    id: 'job101',
    name: '新サービス紹介LPデザイン',
    name_en: 'Landing Page Design for New Service',
    clientName: '株式会社スタートアップ支援',
    clientName_en: 'Startup Support Inc.',
    clientId: 'client101',
    contractorName: null,
    contractorName_en: null,
    contractorId: null,
    contractorResellingRisk: 0,
    clientResellingRisk: 65,
    totalAmount: 80000,
    fundsDeposited: 0,
    fundsReleased: 0,
    status: '募集中',
    status_en: 'Open for Applications',
    dueDate: '2025-07-15',
    completionDate: null,
    description: '7月にリリース予定の新サービスの魅力を伝えるランディングページのデザインをお願いします。ターゲットは20代後半～30代の男女。ワイヤーフレームはこちらで用意します。イラスト制作も可能であれば尚可。',
    description_en: 'Design a landing page to highlight our new service launching in July. Target audience: men and women in their late 20s to 30s. Wireframes will be provided. Illustration skills are a bonus.',
    deliverables: 'LPデザインデータ一式（Figma）',
    deliverables_en: 'All LP design files (Figma)',
    deliverableDetails: 'Figma形式での納品。主要画面（トップ、サービス紹介、料金、会社概要、問い合わせ）のデザイン。スマートフォン表示にも対応。',
    deliverableDetails_en: 'Deliver in Figma format. Includes designs for main screens (Home, Service Introduction, Pricing, About Us, Contact). Must be mobile responsive.',
    acceptanceCriteria: 'デザインカンプ通りの実装、主要ブラウザでの表示確認',
    acceptanceCriteria_en: 'Implementation matches design comp and displays correctly on major browsers',
    acceptanceCriteriaDetails: '納品後5営業日以内に検収。修正は2回までとし、大幅な変更は別途協議。',
    acceptanceCriteriaDetails_en: 'Client will inspect within 5 business days after delivery. Up to 2 rounds of revisions allowed; major changes require separate discussion.',
    scopeOfWork_included: 'LPデザイン制作、レスポンシブデザイン対応、画像素材選定（フリー素材）',
    scopeOfWork_included_en: 'LP design, responsive layout, selection of free image resources',
    scopeOfWork_excluded: 'サーバー設定、ドメイン取得、有料画像素材の購入、テキストライティング',
    scopeOfWork_excluded_en: 'Server setup, domain registration, purchase of paid images, copywriting',
    additionalWorkTerms: '大幅なデザイン変更やページ追加が発生する場合は、別途お見積もりとなります。',
    additionalWorkTerms_en: 'Major design changes or adding pages will require a separate quote.',
    agreementDocLink: null,
    changeOrders: [],
    communicationLogCount: 0,
    lastUpdate: '2025-06-01 10:00',
    hasDispute: false,
    milestones: [
      {
        id: 'job101-m1',
        name: 'デザインカンプ初稿提出',
        name_en: 'Initial Design Draft Submission',
        amount: 40000,
        status: 'pending',
        status_en: 'Pending',
        dueDate: '2025-06-20',
        startDate: '2025-06-10',
        duration: 10,
        description: 'PC・スマホ両対応のデザインカンプを提出。',
        description_en: 'Submit design comp for both PC and smartphone.',
      },
      {
        id: 'job101-m2',
        name: '最終デザインデータ納品',
        name_en: 'Final Design Data Delivery',
        amount: 40000,
        status: 'pending',
        status_en: 'Approved',
        dueDate: '2025-07-10',
        startDate: '2025-06-21',
        duration: 19,
        description: '修正対応後、デザインデータ一式を納品。',
        description_en: 'Deliver all design files after revisions.',
      },
    ],
    requiredSkills: [
      'Webデザイン',
      'LP制作',
      'Figma',
      'レスポンシブデザイン',
    ],
    requiredSkills_en: [
      'Web Design',
      'LP Creation',
      'Figma',
      'Responsive Design',
    ],
    clientRating: { averageScore: 4.5, totalReviews: 12 },
    imageUrl:
      'https://placehold.co/600x400/7C3AED/FFFFFF?text=LP%E3%83%87%E3%82%B6%E3%82%A4%E3%83%B3',
    allowSubcontracting: false,
    aiRecommendationScore: 0.9,
    aiRecommendationReason: 'あなたのスキルはこの案件に最適です。',
    aiRecommendationReason_en: 'Your skills are a great fit for this project.',
    proposals: [
      {
        id: 'prop_user555_for_job101',
        contractorId: 'user555',
        contractorName: '田中 さとし',
        contractorName_en: 'Satoshi Tanaka',
        contractorReputation: {
          totalReviews: 15,
          skillsCertified: ['Webデザイン'], // 現行表記に統一
        },
        proposalText: 'LPデザインの経験豊富です。Figmaでの作成、レスポンシブ対応可能です。ぜひ担当させてください。',
        proposalText_en: 'I have extensive experience in LP design. I can create in Figma and support responsive design. I would love to take on this project.',
        proposedAmount: 78000,
        estimatedDeliveryTime: '2週間',
        estimatedDeliveryTime_en: '2 weeks',
        submissionDate: '2025-06-06',
        status: 'pending_review',
      },
    ],
  },
  // job103
  {
    id: 'job103',
    name: 'PR記事作成依頼（月5本）',
    name_en: 'PR Article Writing Request (5 per month)',
    clientName: '田中 さとし',
    clientName_en: 'Satoshi Tanaka',
    clientId: 'user555',
    contractorName: null,
    contractorId: null,
    contractorResellingRisk: 0,
    clientResellingRisk: 20,
    totalAmount: 50000,
    fundsDeposited: 0,
    fundsReleased: 0,
    status: '募集中',
    status_en: 'Open for Applications',
    dueDate: '2025-06-30',
    description: '弊社サービスの認知度向上のため、指定キーワードに基づいたPR記事を月5本作成・納品していただけるライター様を募集します。1記事あたり2000字程度。SEOライティング経験者歓迎。継続依頼の可能性あり。',
    description_en: 'We are seeking a writer to create and deliver 5 PR articles per month based on specified keywords to increase awareness of our service. Each article should be around 2,000 characters. SEO writing experience is welcome. Possible ongoing work.',
    deliverables: 'PR記事5本（Word形式）、各記事のキーワードリスト',
    deliverables_en: '5 PR articles (Word format), keyword list for each article',
    deliverableDetails: '各記事2000字以上。指定キーワードを適切に含み、読者の検索意図に合致する内容であること。コピ―コンテンツでないこと。',
    deliverableDetails_en: 'Each article must be at least 2,000 characters, include specified keywords appropriately, and match the reader’s search intent. No duplicate content.',
    acceptanceCriteria: '指定キーワードでの検索順位目標達成、誤字脱字なし',
    acceptanceCriteria_en: 'Achieve target search ranking for specified keywords, no typos or errors',
    acceptanceCriteriaDetails: '納品後3営業日以内に検収。修正は各記事1回まで。文法・表現の誤りがないこと。',
    acceptanceCriteriaDetails_en: 'Inspection within 3 business days after delivery. Each article may be revised once. No grammatical or expression errors.',
    scopeOfWork_included: '記事執筆、キーワードリサーチ、SEO観点での構成案作成',
    scopeOfWork_included_en: 'Article writing, keyword research, creating structure proposals from an SEO perspective',
    scopeOfWork_excluded: '画像選定、CMSへの入稿作業、SNSでの拡散',
    scopeOfWork_excluded_en: 'Image selection, CMS posting, social media sharing',
    additionalWorkTerms: '追加記事は1本あたり10,000円（税別）とします。',
    additionalWorkTerms_en: 'Additional articles will be charged at ¥10,000 (excluding tax) per article.',
    agreementDocLink: null,
    changeOrders: [],
    communicationLogCount: 0,
    lastUpdate: '2025-06-02 12:00',
    hasDispute: false,
    milestones: [
      {
        id: 'job103-m1',
        name: '初回記事5本納品',
        name_en: 'First Delivery of 5 Articles',
        amount: 50000,
        status: 'pending',
        status_en: 'Pending',
        dueDate: '2025-06-30',
        startDate: '2025-06-20',
        duration: 10,
        description: '指定キーワードに基づく記事5本',
        description_en: '5 articles based on specified keywords',
      },
    ],
    requiredSkills: ['SEOライティング', 'コンテンツ作成', 'キーワードリサーチ'],
    requiredSkills_en: ['SEO Writing', 'Content Creation', 'Keyword Research'],
    clientRating: { averageScore: null, totalReviews: 0 },
    imageUrl: 'https://placehold.co/600x400/DB2777/FFFFFF?text=PR%E8%A8%98%E4%BA%8B%E4%BD%9C%E6%88%90',
    allowSubcontracting: true,
    aiRecommendationScore: 0.75,
    aiRecommendationReason: 'あなたの「コンテンツ作成」スキルと過去の類似案件実績に合致しています。',
    aiRecommendationReason_en: 'Your content creation skills and past experience with similar projects are a great match.',
    proposals: [
      {
        id: 'prop001',
        projectId: 'job103',
        contractorId: 'user888',
        contractorName: '鈴木 一郎',
        contractorName_en: 'Ichiro Suzuki',
        contractorReputation: {
          averageScore: 4.9,
          totalReviews: 25,
          identityVerified: true,
          skillsCertified: ['SEO Master'],
        },
        contractorResellingRisk: 15,
        proposalText: 'SEOライティング歴5年の鈴木と申します。貴社サービスに貢献できる質の高い記事を迅速に作成いたします。過去実績はポートフォリオをご覧ください。月5本、2000字/記事でご提案の予算内で対応可能です。納期も柔軟に対応できます。',
        proposalText_en: 'My name is Ichiro Suzuki and I have 5 years of experience in SEO writing. I will quickly create high-quality articles to contribute to your service. Please see my portfolio for past work. I can deliver 5 articles per month, 2,000 characters each, within your proposed budget. I am flexible with deadlines.',
        proposedAmount: 50000,
        estimatedDeliveryTime: '各記事3営業日以内',
        estimatedDeliveryTime_en: 'Within 3 business days per article',
        submissionDate: '2025-06-03',
        status: 'pending_review',
      },
      {
        id: 'prop002',
        projectId: 'job103',
        contractorId: 'user999',
        contractorName: '高橋 文子',
        contractorName_en: 'Ayako Takahashi',
        contractorReputation: {
          averageScore: 4.7,
          totalReviews: 18,
          identityVerified: false,
          skillsCertified: [],
        },
        contractorResellingRisk: 5,
        proposalText: 'ライターの高橋です。特にIT・テクノロジー分野のPR記事を得意としております。キーワードリサーチから構成案作成、執筆まで一貫して対応可能です。ご提示の条件でぜひお受けしたく存じます。',
        proposalText_en: 'I am Ayako Takahashi, a writer specializing in PR articles for IT and technology fields. I can handle everything from keyword research and structure proposals to writing. I would be happy to accept your offer under the stated conditions.',
        proposedAmount: 48000,
        estimatedDeliveryTime: '月5本を月末までに納品',
        estimatedDeliveryTime_en: 'Deliver 5 articles by the end of the month',
        submissionDate: '2025-06-04',
        status: 'pending_review',
      },
    ],
    comment_en: null,
    contractorResponse_en: null,
  },
  // job_dispute_01
  {
    id: 'job_dispute_01',
    name: 'ウェブサイトリニューアル（協議中サンプル）',
    name_en: 'Website Renewal (Sample in Discussion)',
    clientName: '株式会社ABCテック',
    clientName_en: 'ABC Tech Inc.',
    clientId: 'clientABC',
    contractorName: '田中 さとし',
    contractorName_en: 'Satoshi Tanaka',
    contractorId: 'user555',
    contractorResellingRisk: 80,
    clientResellingRisk: 50,
    totalAmount: 150000,
    fundsDeposited: 100000,
    fundsReleased: 20000,
    status: '協議中',
    status_en: 'In Discussion',
    dueDate: '2025-05-01',
    completionDate: null,
    description: '既存コーポレートサイトのフルリニューアル。デザインとコーディングを含む。現在、仕様変更の範囲について依頼者と意見の相違が発生し、協議中です。',
    description_en: 'Complete renewal of the existing corporate website, including design and coding. Currently in discussion due to differences in the scope of changes with the client.',
    deliverables: 'ウェブサイト一式（HTML, CSS, JS, 画像素材）、デザインカンプ（Photoshop）',
    deliverables_en: 'Full website (HTML, CSS, JS, image assets), design comps (Photoshop)',
    deliverableDetails: '全10ページ構成。お問い合わせフォーム機能を含む。',
    deliverableDetails_en: 'Consists of 10 pages in total. Includes contact form functionality.',
    acceptanceCriteria: '全ページのデザインと機能が仕様書通りであること',
    acceptanceCriteria_en: 'All pages match the design and functionality specifications.',
    acceptanceCriteriaDetails: 'テスト環境での動作確認後、依頼者による承認。',
    acceptanceCriteriaDetails_en: 'Operation confirmed in the test environment, then client approval.',
    scopeOfWork_included: 'デザイン制作（トップページ＋下層9ページ）、HTML/CSS/JSコーディング、レスポンシブ対応、基本的なSEO設定',
    scopeOfWork_included_en: 'Design (top page + 9 subpages), HTML/CSS/JS coding, responsive support, basic SEO settings.',
    scopeOfWork_excluded: 'サーバー移管作業、公開後の保守運用、コンテンツ作成（テキスト・画像素材は依頼者支給）',
    scopeOfWork_excluded_en: 'Server migration, post-launch maintenance, content creation (text/images provided by client).',
    additionalWorkTerms: '仕様変更や追加ページ作成は、都度協議の上、追加費用を決定する。',
    additionalWorkTerms_en: 'Scope changes or additional pages: cost will be determined through discussion each time.',
    agreementDocLink: 'agreement_dispute_01.pdf',
    changeOrders: [
      {
        id: 'co_d1',
        date: '2025-04-15',
        description: '追加ページ作成依頼（未合意）',
        description_en: 'Request for additional page creation (not yet agreed)',
      },
    ],
    communicationLogCount: 35,
    lastUpdate: '2025-06-01 15:00',
    hasDispute: true,
  proposals: [],
    disputeDetails: '仕様変更の範囲と追加費用について合意に至らず、作業が中断しています。',
    disputeDetails_en: 'Work is suspended due to lack of agreement on the scope changes and additional costs.',
    milestones: [
      {
        id: 'job_d01-m1',
        name: 'デザインカンプ承認',
        name_en: 'Design Comp Approval',
        amount: 50000,
        status: 'approved',
        dueDate: '2025-04-10',
        description: 'トップページと主要下層ページのデザイン承認済み。',
        description_en: 'Designs for the top page and main subpages have been approved.',
      },
      {
        id: 'job_d01-m2',
        name: 'コーディング中間提出',
        name_en: 'Coding Interim Submission',
        amount: 50000,
        status: 'submitted',
        dueDate: '2025-04-25',
        description: '主要機能実装済み。追加仕様について協議中。',
        description_en: 'Main features have been implemented. Additional specifications are under discussion.',
      },
      {
        id: 'job_d01-m3',
        name: '最終納品と検収',
        name_en: 'Final Delivery & Inspection',
        amount: 50000,
        status: 'pending',
        dueDate: '2025-05-10',
        description: '全機能の結合テスト完了後、最終確認。',
        description_en: 'Final confirmation after all features have been implemented.',
      },
    ],
    requiredSkills: ['HTML', 'CSS', 'JavaScript', 'PHP'],
    requiredSkills_en: ['HTML', 'CSS', 'JavaScript', 'PHP'],
    clientRating: { averageScore: 4.0, totalReviews: 3 },
    allowSubcontracting: false,
  },
  // job105
  {
    id: 'job105',
    name: '簡単なデータ入力作業',
    name_en: 'Simple Data Entry Task',
    clientName: '株式会社データサービス',
    clientName_en: 'Data Service Inc.',
    clientId: 'clientXYZ',
    contractorName: null,
    contractorId: null,
    totalAmount: 20000,
    status: '募集中',
    dueDate: '2025-07-20',
    description: '指定されたフォーマットへのデータ入力作業です。正確性が求められます。週に10時間程度の作業を想定しています。',
    description_en: 'Enter data into a specified format. Accuracy is required. Expected workload: about 10 hours per week.',
    requiredSkills: ['データ入力', 'Excel', '注意力'],
    requiredSkills_en: ['Data Entry', 'Excel', 'Attention to Detail'],
    clientRating: { averageScore: 4.0, totalReviews: 3 },
    allowSubcontracting: false,
    aiRecommendationScore: 0.2,
    proposals: [],
    milestones: [
      {
        id: 'job105-m1',
        name: 'データ入力完了',
        name_en: 'Data Entry Completion',
        amount: 20000,
        status: 'pending',
        dueDate: '2025-07-20',
        description: '全データ入力完了',
        description_en: 'All data entry completed.',
      },
    ],
  },
  // id: job4
  {
    id: 'job4',
    name: 'アプリUI改善提案',
    name_en: 'App UI Improvement Proposal',
    clientName: 'スタートアップY',
    clientName_en: 'Startup Y',
    clientId: 'clientY',
    contractorName: '田中 さとし',
    contractorName_en: 'Satoshi Tanaka',
    contractorId: 'user555',
    contractorResellingRisk: 0,
    clientResellingRisk: 0,
    totalAmount: 120000,
    fundsDeposited: 120000,
    fundsReleased: 0,
    status: '作業中',
    status_en: 'In Progress',
    dueDate: '2025-07-05',
    description: '既存モバイルアプリのUI改善提案とモック作成。週1回の定例ミーティング必須。',
    description_en: 'Propose UI improvements and create mockups for an existing mobile app. Weekly meetings are required.',
    deliverables: 'UI改善提案資料（PDF）、主要画面モックアップ（Figma）',
    deliverables_en: 'UI improvement proposal document (PDF), main screen mockups (Figma)',
    deliverableDetails: '現状分析レポート、UI改善案（3パターン）、主要5画面のインタラクティブモックアップ。',
    deliverableDetails_en: 'Report on current state analysis, 3 UI improvement ideas, and interactive mockups for 5 main screens.',
    acceptanceCriteria: '提案内容がユーザビリティテストで高評価を得ること',
    acceptanceCriteria_en: 'Proposal receives high marks in usability testing.',
    acceptanceCriteriaDetails: 'ユーザビリティテストは依頼者側で実施。テスト結果に基づき、致命的な問題がないことを確認。',
    acceptanceCriteriaDetails_en: 'Usability testing will be conducted by the client. No critical issues should be found based on the test results.',
    scopeOfWork_included: '現状分析、ユーザーインタビュー（3名まで）、競合調査、改善提案、ワイヤーフレーム作成、モックアップ作成',
    scopeOfWork_included_en: 'Current state analysis, user interviews (up to 3 people), competitor research, improvement proposals, wireframe creation, mockup creation.',
    scopeOfWork_excluded: '実装、A/Bテストの実施、ユーザーインタビュー対象者のリクルーティング',
    scopeOfWork_excluded_en: 'Implementation, A/B testing, recruiting interview subjects.',
    additionalWorkTerms: '追加画面のモック作成は1画面あたり20,000円。ユーザビリティテストの設計・実施サポートは別途お見積もり。',
    additionalWorkTerms_en: 'Additional mockups: ¥20,000 per screen. Usability test design/support will be quoted separately.',
    agreementDocLink: 'agreement_project4.pdf',
    changeOrders: [],
    communicationLogCount: 12,
    lastUpdate: '2025-05-30 11:00',
    hasDispute: false,
    milestones: [
      {
        id: 'm4-1',
        name: '現状分析と課題整理',
        name_en: 'Current State Analysis & Issue Identification',
        // ...other milestone properties as needed...
      },
    ],
  },
  // ...existing code...
  {
    id: 'job106',
    name: 'ECサイト新機能開発',
    name_en: 'New Feature Development for EC Site',
    clientName: '株式会社EコマースX',
    clientName_en: 'E-Commerce X Inc.',
    clientId: 'clientECX',
    contractorName: null,
    contractorId: null,
    totalAmount: 300000,
    fundsDeposited: 0,
    fundsReleased: 0,
    status: '募集中',
    dueDate: '2025-08-30',
    description: '既存ECサイトに決済機能とユーザーレビュー機能を追加開発。React, Node.jsの経験必須。',
    description_en: 'Develop and add payment and user review features to an existing EC site. Experience with React and Node.js required.',
    requiredSkills: ['React', 'Node.js', 'API連携'],
    requiredSkills_en: ['React', 'Node.js', 'API Integration'],
    clientRating: { averageScore: 4.7, totalReviews: 8 },
    allowSubcontracting: false,
    aiRecommendationScore: 0.85,
    aiRecommendationReason_en: 'Your skills in React and Node.js are a perfect match for this project!',
    proposals: [],
    milestones: [
      {
        id: 'job106-m1',
        name: '要件定義と設計',
        name_en: 'Requirements Definition & Design',
        amount: 100000,
        status: 'pending',
        dueDate: '2025-07-15',
        description: '新機能の要件定義とシステム設計を完了。',
        description_en: 'Complete requirements definition and system design for new features.'
      },
      {
        id: 'job106-m2',
        name: '開発とテスト',
        name_en: 'Development & Testing',
        amount: 150000,
        status: 'pending',
        dueDate: '2025-08-15',
        description: '決済機能とレビュー機能のフロントエンド・バックエンド開発および単体テスト。',
        description_en: 'Develop and unit test payment and review features for both frontend and backend.'
      },
      {
        id: 'job106-m3',
        name: '最終納品と結合テスト',
        name_en: 'Final Delivery & Integration Testing',
        amount: 50000,
        status: 'pending',
        dueDate: '2025-08-30',
        description: '全機能の結合テスト完了後、本番環境へのデプロイ支援と最終納品。',
        description_en: 'Complete integration testing for all features, assist with production deployment, and deliver final assets.'
      }
    ]
  }
];

// --- Exports for each app section (after dashboardAllProjects definition) ---
// Dashboard: 案件一覧や進捗表示用
export const dashboardProjects = dashboardAllProjects.filter(p => [
  'job101', 'job103', 'job1', 'job4', 'job_dispute_01'
].includes(p.id));



// // Command UI: コマンドUI用の案件
// export const commandUIProjects = dashboardAllProjects.filter(p => [
//   'job106'
// ].includes(p.id));