name: CI

on:
  push:
    branches: [ main, 'feature/**' ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies (allow legacy peer deps)
        run: |
          npm config set legacy-peer-deps true
          npm ci

      - name: Run tests
        run: CI=true npm test -- --watchAll=false --runInBand
